evbeda/edagames-django

development/forms.py
development/views.py
requirements.txt

Docker isn't work yet for both images (Django and Server).

[PATCH] EDA-1241 Conflicts version resolved

---

development/forms.py

Create a tuple with indexes and user_name to show in the Web.

[PATCH] EDA-1241 Fix get_oneline_users method

---

development/forms.py

[PATCH] EDA-1241 Fix json parse of data from Server

---

development/forms.py

- Now a challenge can be sent from Web using Pedro bot.

[PATCH] EDA-1335 Replace mock my_bots in django for bots list in client repo

---

development/bot_handler.py
development/forms.py
development/tests.py
development/views.py

- Modify the hardcoded my_bots for a method to list the real my online bots.
- I need help to test the method `get_data_users`
- The rest of the code is tested.

[MINOR] EDA-1283 filter my bots

---

development/views.py

- Matches filter if the user online played as player1 or player2.

[MINOR] EDA-1361 Filter correct matches by user online

---

development/serializer.py
development/views_api.py

- Now a match contains the users besides the bot names.

[PATCH] Add users match

---

auth_app/pipeline.py
development/token.py

Now token is build with user.email

EDA-1391 Refactor token username

---

edagames/settings.py
tournaments/admin.py
tournaments/apps.py
tournaments/models.py
tournaments/tests.py
tournaments/views.py

-To initialize tournaments app.

Tournaments app

---

auth_app/admin.py
tournaments/admin.py

Adds to admin panel:
- Bot
- Tournament

Fix admin site

---

development/views.py
edagames/settings.py

Fix color message when a bot is created or not.

[PATCH] EDA-1235 color bot created

---

development/challenge_request.py
development/views.py

Moves post method to send a challenge into another script to be reused in tournaments.

[MINOR] EDA-1417 post server method

---

development/views.py

Stays on the same page to create another bot.

[PATCH] EDA-1408 Returns to addbot view if it can't create a bot

---

auth_app/pipeline.py
development/encode_jwt.py
development/views.py

Make this method reusable to encode other data.

[MINOR] EDA-1367 refactor encode

---

.coveragerc
edagames/urls.py
static/js/create_tournament.js
templates/base.html
tournaments/forms.py
tournaments/templates/tournaments/create_tournaments.html
tournaments/tests.py
tournaments/tests/test_views.py
tournaments/urls.py
tournaments/views.py

A CreatedTournamentView was created. Also a template with a js file.

[MINOR] EDA-1264 Create tournament view for new tournament

---

auth_app/templates/auth_app/faq.html
auth_app/tests/test_faq_view.py
auth_app/tests/tests.py
auth_app/urls.py
auth_app/views.py
static/css/sb-admin-2.css
templates/base.html

Adds frequently asked questions to the Web.

[MINOR] EDA-1436 FAQ view

---

templates/base.html

Adding authentication to submenu: Createa Tournament.

[PATCH]-EDA-1433- Remove create tournament option in sidebar for normal users.

---

auth_app/templates/auth_app/home.html
auth_app/urls.py
auth_app/views.py
templates/base.html

This is a major because we change base.html template, and also a template of a previous view.

[MINOR]- EDA- 1366 Add information to the homepage

---

entrypoint.sh

Fixing the error  ```ModuleNotFoundError: No module named 'settings'```

[PATCH] Fix path for settings module in entrypoint

---

auth_app/urls.py
auth_app/views.py
templates/base.html

Change Profile url to http://localhost:8000/profile/ to avoid users seeing other profiles.

[PATCH]Fix url profile to get only the user in the session

---

auth_app/templates/auth_app/home.html

Add a link to the official documentation for EDA users.

Add documentation link to home page

---

templates/base.html
tournaments/forms.py
tournaments/templates/tournaments/tournament_generator.html
tournaments/tests/test_tournaments.py
tournaments/urls.py
tournaments/views.py

It is a view to generating multiples tournaments given a number of max players for each tournament.

[MINOR] Create Tournament Generator view 

---

auth_app/models.py
auth_app/tests/tests.py
development/models.py
development/tests/test_match_models.py
tournaments/common/tournament_utils.py
tournaments/models.py
tournaments/tests/test_tournaments.py

Fix Tournament Results, add string representation to models

---

development/templates/development/match_details.html

Fix match logs view

---

development/common/match_utils.py
development/tests/test_match_history_view.py

Sort match table by date_match desc

---

development/templates/development/match_details.html
development/templates/development/match_history.html
tournaments/templates/tournaments/tournaments_history.html

Add messages for empty tables

---

tournaments/templates/tournaments/tournaments_pending.html
tournaments/tests/test_delete_tournament.py
tournaments/urls.py
tournaments/views.py

Add delete option for pending tournaments that are not going to be started

[MINOR] Add delete option for pending tournaments

---

edagames/settings/local.py

After installing and running docker. Django app has problems with the server and does not start in the local environment, or develop environment.
To solve this. Change local.py in the settings of Django and change the file to local.py see to configure

[PATCH][EDA-1579] change local environment

---

edagames/settings/prod.py

- Add a function `get_secret` with `boto3` to get the username and the password for the database from ` AWS Secret Manager`. 
- With the secret, Django can get the `engine`, `name`, `username`, `password`, `host`, and `port` of Aurora, needed for the database settings.

[MINOR][EDA-1720] - Django - change database settings to connect with Aurora RDS

---

edagames/settings/prod.py

add json loads to get the secret from AWS Secret Manager to convert it to a dictionary

[PATCH] add json loads

---

edagames/settings/prod.py

[PATCH ]changing ENGINE value for 'ENGINE': 'django.db.backends.mysql'

---

development/common/readme.txt

Needed to add a new file, so changes are detected and CircleCI can integrate into the project. readme.txt file was added.

readme added to text CircleCI

---

static/css/style_tornament_result.css
static/js/logs_page.js
static/js/tournament_results_page.js
templates/base.html
tournaments/templates/tournaments/tournament_results.html

Currently, The table only sort for player points. With this change, you can sort for all values of the table.

[PATCH][EDA-1794]Add button to sort table

---

.circleci/config.yml

With this PR Circleci Execute a jest tests when trying to make a PR. This to prevent Js fails

[PATCH][EDA-1796] Change circle-ci file

---

development/templates/development/my_bots.html
static/js/my_bot_page.js
static/js/my_bot_pages.js
templates/base.html

When the user copies the bot token  the button changes his color

[EDA-1776][PATCH] Change button color

---

static/js/tournament_results_page.js

When the old sort function. Have problems with numbers like total wins or scores. When I tried fixing it. I had problems with infinite loops. So I decided to change it.
With this new function don't have loops problems and sort numbers and words

[MAJOR][EDA-1807] change sort function
